### ISSUE TITLE
Problems with HTTPS and EventStream

### ISSUE THREAD

**Issue by hoffmannjan** [casper-ecosystem/casper-client-sdk#202]
So there are reported problems with HTTPS and EventStream

```
TypeError [ERR_INVALID_PROTOCOL]: Protocol "https:" not supported. Expected "http:"
    at new NodeError (node:internal/errors:371:5)
    at new ClientRequest (node:_http_client:158:11)
    at request (node:http:96:10)
    at Object.get (node:http:107:15)
    at e.start (/Users/janhoffmann/Desktop/cep47/node_modules/casper-js-sdk/dist/lib.node.js:1:121185)
    at CEP47Client.ContractClient.handleEvents (/Users/janhoffmann/Desktop/cep47/node_modules/casper-js-client-helper/dist/casper-contract-client.js:143:12)
    at CEP47Client.onEvent (/Users/janhoffmann/Desktop/cep47/node_modules/casper-cep47-js-client/dist/cep47client.js:601:21)
    at run (/Users/janhoffmann/Desktop/cep47/index.js:7:35)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 'ERR_INVALID_PROTOCOL'
}
```

**Comment by hoffmannjan** [comment]
I think I know where is the problem, [we're using `http`](https://github.com/casper-ecosystem/casper-js-sdk/blob/dev/src/services/EventStream.ts#L2) so we will need to replace it (this is because most of the nodes that we tested was only running over HTTP).

This needs to be replaced and polyfilled for a browsers versions. So the task should be pretty simple - but due to lack of test coverage in `EventStream` we will need to **preferably** add this missing tests to make sure its working.

**Comment by hoffmannjan** [comment]
@gyroflaw already have issues with this part of SDK - we discussed and decided that this might be the next task for him. Estimated this to 13p as it might involve some changes in how EvenStream behave which will require extensive testing.
